# Singularity v0.1.1
# Code Pass 12 / v0.1.1 constants.

# Debug modes
DEBUG_OFF = "OFF"
DEBUG_BASIC = "BASIC"
DEBUG_STANDARD = "STANDARD"
DEBUG_DEEP = "DEEP"
DEBUG_FULL = "FULL"

DEBUG_MODES = [
    DEBUG_OFF,
    DEBUG_BASIC,
    DEBUG_STANDARD,
    DEBUG_DEEP,
    DEBUG_FULL,
]

# Technical types
TECH_TEXT = "TEXT"
TECH_IMAGE = "IMAGE"
TECH_LATENT = "LATENT"
TECH_NOISE = "NOISE"
TECH_CONDITIONING = "CONDITIONING"
TECH_DELTA = "DELTA"
TECH_UNKNOWN = "UNKNOWN"

TECHNICAL_TYPES_CODE_PASS_6 = [
    TECH_TEXT,
    TECH_IMAGE,
    TECH_LATENT,
    TECH_NOISE,
    TECH_CONDITIONING,
    TECH_DELTA,
    TECH_UNKNOWN,
]

# Formula roles
ROLE_OUTCOME_PREVIOUS = "OutcomePrevious"
ROLE_OUTCOME_NEXT = "OutcomeNext"
ROLE_STRATEGY_CURRENT = "StrategyCurrent"
ROLE_STRATEGY_CANDIDATE = "StrategyCandidate"
ROLE_STRATEGY_CARRIER = "StrategyCarrier"
ROLE_OBSERVED_BEHAVIOR = "ObservedBehaviorCurrent"
ROLE_UNKNOWN = "UnknownRole"

FORMULA_ROLES_CODE_PASS_6 = [
    "AUTO",
    ROLE_STRATEGY_CURRENT,
    ROLE_STRATEGY_CANDIDATE,
    ROLE_STRATEGY_CARRIER,
    ROLE_OUTCOME_PREVIOUS,
    ROLE_OUTCOME_NEXT,
    ROLE_OBSERVED_BEHAVIOR,
    ROLE_UNKNOWN,
]

# Representation spaces
SPACE_TEXT = "TEXT_SPACE"
SPACE_IMAGE = "IMAGE_SPACE"
SPACE_LATENT = "LATENT_SPACE"
SPACE_NOISE = "NOISE_SPACE"
SPACE_CONDITIONING = "CONDITIONING_SPACE"
SPACE_DELTA = "DELTA_SPACE"
SPACE_EVENT = "EVENT_SPACE"
SPACE_UNKNOWN = "UNKNOWN_SPACE"

# Relation types
REL_EQUALS_AS_EVENT = "EQUALS_AS_EVENT"
REL_PROJECTS_TO = "PROJECTS_TO"
REL_GUIDES = "GUIDES"
REL_CONSTRAINS = "CONSTRAINS"
REL_TRANSFORMS_INTO = "TRANSFORMS_INTO"
REL_EXPANDS_TO = "EXPANDS_TO"
REL_COLLAPSES_INTO = "COLLAPSES_INTO"
REL_UNKNOWN = "UNKNOWN_RELATION"

RELATION_TYPES_CODE_PASS_6 = [
    REL_EQUALS_AS_EVENT,
    REL_PROJECTS_TO,
    REL_GUIDES,
    REL_CONSTRAINS,
    REL_TRANSFORMS_INTO,
    REL_EXPANDS_TO,
    REL_COLLAPSES_INTO,
    REL_UNKNOWN,
]

# Equality status
EQ_UNKNOWN = "UNKNOWN"
EQ_PASS = "PASS"
EQ_WEAK_PASS = "WEAK_PASS"
EQ_WEAK_FAIL = "WEAK_FAIL"
EQ_FAIL = "FAIL"

EQUALITY_STATUS_CODE_PASS_6 = [
    EQ_UNKNOWN,
    EQ_PASS,
    EQ_WEAK_PASS,
    EQ_WEAK_FAIL,
    EQ_FAIL,
]

# Conflict severity
SEV_INFO = "INFO"
SEV_LOW = "LOW"
SEV_MEDIUM = "MEDIUM"
SEV_HIGH = "HIGH"
SEV_CRITICAL = "CRITICAL"

CONFLICT_SEVERITIES = [
    SEV_INFO,
    SEV_LOW,
    SEV_MEDIUM,
    SEV_HIGH,
    SEV_CRITICAL,
]

# Conflict types v0.1
CONFLICT_NO_READER_FOUND = "NO_READER_FOUND"
CONFLICT_ROLE_UNKNOWN = "ROLE_UNKNOWN"
CONFLICT_EMPTY_RELATION = "EMPTY_RELATION"
CONFLICT_MISSING_SIGNAL = "MISSING_SIGNAL"
CONFLICT_INVALID_SIGNAL_ID = "INVALID_SIGNAL_ID"
CONFLICT_PACKET_MISSING = "PACKET_MISSING"

# Boundary conflicts
CONFLICT_DELTA_UNAVAILABLE = "DELTA_UNAVAILABLE"
CONFLICT_BOUNDARY_SHAPE_MISMATCH = "BOUNDARY_SHAPE_MISMATCH"
CONFLICT_BOUNDARY_TYPE_MISMATCH = "BOUNDARY_TYPE_MISMATCH"
CONFLICT_DELTA_OVERCHANGE = "DELTA_OVERCHANGE"
CONFLICT_DELTA_UNDERCHANGE = "DELTA_UNDERCHANGE"


# Sampler boundary conflicts
CONFLICT_SAMPLER_BOUNDARY_SHAPE_MISMATCH = "SAMPLER_BOUNDARY_SHAPE_MISMATCH"
CONFLICT_SAMPLER_DELTA_UNAVAILABLE = "SAMPLER_DELTA_UNAVAILABLE"
CONFLICT_SAMPLER_METADATA_MISSING = "SAMPLER_METADATA_MISSING"


# Structured strategy warnings
CONFLICT_NO_STABLE_ANCHORS = "NO_STABLE_ANCHORS"
CONFLICT_NO_ACTIVE_CHANGES = "NO_ACTIVE_CHANGES"
CONFLICT_NO_CONTACT_RULE = "NO_CONTACT_RULE"
CONFLICT_NO_ENDPOINT = "NO_ENDPOINT"
CONFLICT_NO_FORBIDDEN_DRIFT = "NO_FORBIDDEN_DRIFT"


# Noise strategy conflicts
CONFLICT_NOISE_MISSING = "NOISE_MISSING"
CONFLICT_NOISE_SHAPE_UNKNOWN = "NOISE_SHAPE_UNKNOWN"
CONFLICT_NOISE_READER_FAILED = "NOISE_READER_FAILED"
CONFLICT_NOISE_LATENT_SHAPE_MISMATCH = "NOISE_LATENT_SHAPE_MISMATCH"


# Core Alpha info conflicts / route warnings
CONFLICT_ALPHA_ROUTE_MISSING = "ALPHA_ROUTE_MISSING"
CONFLICT_ALPHA_PARTIAL_INPUT = "ALPHA_PARTIAL_INPUT"


# Wan adapter conflicts / route warnings
CONFLICT_WAN_HIGH_LOW_ROUTE_MISSING = "WAN_HIGH_LOW_ROUTE_MISSING"
CONFLICT_WAN_TEMPORAL_ROUTE_UNKNOWN = "WAN_TEMPORAL_ROUTE_UNKNOWN"
CONFLICT_WAN_PROMPT_ROUTE_WEAK = "WAN_PROMPT_ROUTE_WEAK"
CONFLICT_WAN_SOURCE_ROUTE_MISSING = "WAN_SOURCE_ROUTE_MISSING"
CONFLICT_WAN_DECODE_ROUTE_MISSING = "WAN_DECODE_ROUTE_MISSING"


# Frozen node constants
FROZEN_MODE_BASIC = "BASIC"
FROZEN_MODE_RESEARCH = "RESEARCH"
FROZEN_MODE_WAN = "WAN"

REPORT_DETAIL_COMPACT = "COMPACT"
REPORT_DETAIL_STANDARD = "STANDARD"
REPORT_DETAIL_FULL = "FULL"

# Frozen node conflicts / diagnostics
CONFLICT_FROZEN_ROUTE_MISSING = "FROZEN_ROUTE_MISSING"
CONFLICT_FROZEN_PARTIAL_OBSERVABILITY = "FROZEN_PARTIAL_OBSERVABILITY"
CONFLICT_PASSTHROUGH_OUTPUT_MISSING = "PASSTHROUGH_OUTPUT_MISSING"
CONFLICT_PACKET_BRANCH_CREATED = "PACKET_BRANCH_CREATED"
CONFLICT_REPORT_SAVE_FAILED = "REPORT_SAVE_FAILED"

